package config

import (
	"crypto/rand" // Added
	"encoding/hex"  // Added
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

const (
	configDirName  = ".filesync"
	configFileName = "config.json"
)

// DeviceConfig holds the configuration for a single remote device.
type DeviceConfig struct {
	Name    string `json:"name"` // User-friendly name, also used as key in map
	Address string `json:"address"`
	Port    int    `json:"port"`
	Key     string `json:"key"` // Pre-shared key
}

// Config is the main configuration structure.
type Config struct {
	DeviceID string                  `json:"deviceID"` // Unique ID for this filesync instance
	Devices  map[string]DeviceConfig `json:"devices"`
}

// NewConfig creates and returns an empty Config, ensuring Devices map is initialized.
func NewConfig() *Config {
	return &Config{
		Devices: make(map[string]DeviceConfig),
	}
}

// getConfigPath constructs the full path to the config file.
func getConfigPath(baseFolder string) (string, error) {
	absBaseFolder, err := filepath.Abs(baseFolder)
	if err != nil {
		return "", fmt.Errorf("failed to get absolute path for base folder '%s': %w", baseFolder, err)
	}
	return filepath.Join(absBaseFolder, configDirName, configFileName), nil
}

// LoadConfig loads the configuration from .filesync/config.json in the baseFolder.
// If the file doesn't exist, it returns a new Config with an initialized empty map for Devices
// and a newly generated DeviceID.
func LoadConfig(baseFolder string) (*Config, error) {
	configFilePath, err := getConfigPath(baseFolder)
	if err != nil {
		return nil, err
	}

	var cfg Config
	// deviceIDWasGenerated := false // Flag to indicate if we generated a new ID -- REMOVED

	if _, err := os.Stat(configFilePath); os.IsNotExist(err) {
		fmt.Printf("Config file '%s' not found. Initializing new config.\n", configFilePath)
		cfg = *NewConfig() // Get a new config struct
		// DeviceID will be generated below if empty
	} else if err != nil {
		return nil, fmt.Errorf("failed to stat config file '%s': %w", configFilePath, err)
	} else {
		// File exists, try to read and unmarshal
		data, err := os.ReadFile(configFilePath)
		if err != nil {
			return nil, fmt.Errorf("failed to read config file '%s': %w", configFilePath, err)
		}

		if len(data) == 0 { // Handle empty file case
			fmt.Printf("Config file '%s' is empty. Initializing new config structure.\n", configFilePath)
			cfg = *NewConfig()
			// DeviceID will be generated below if empty
		} else {
			err = json.Unmarshal(data, &cfg)
			if err != nil {
				return nil, fmt.Errorf("failed to unmarshal config data from '%s': %w", configFilePath, err)
			}
			fmt.Printf("Config loaded successfully from '%s'.\n", configFilePath)
		}
	}

	// Ensure Devices map is not nil (it should be handled by NewConfig or if JSON is valid)
	if cfg.Devices == nil {
		cfg.Devices = make(map[string]DeviceConfig)
	}

	// Generate DeviceID if it's empty
	if cfg.DeviceID == "" {
		hostname, errHost := os.Hostname()
		if errHost != nil {
			hostname = "unknownhost"
			fmt.Printf("Warning: Could not get hostname for DeviceID generation: %v\n", errHost)
		}

		randBytes := make([]byte, 4) // 4 bytes = 8 hex chars
		if _, errRand := rand.Read(randBytes); errRand != nil {
			// Fallback if crypto/rand fails, though highly unlikely
			randomHexString := "randerr"
			cfg.DeviceID = fmt.Sprintf("%s-%s", hostname, randomHexString)
			fmt.Printf("Warning: crypto/rand failed for DeviceID generation: %v\n", errRand)
		} else {
			randomHexString := hex.EncodeToString(randBytes)
			cfg.DeviceID = fmt.Sprintf("%s-%s", hostname, randomHexString)
		}

		// deviceIDWasGenerated = true // REMOVED
		fmt.Printf("Generated new DeviceID: %s\n", cfg.DeviceID)
		// Note: LoadConfig doesn't save. The caller (e.g. init, listen) should save if a new ID was generated.
		// However, for robustness, if it's the first time a config is effectively created (file not found or empty),
		// and a DeviceID is generated, it's good practice for LoadConfig to indicate this state,
		// or for the caller to be aware. The subtask implies init command will save it.
		// For listen command, it will also need to save if ID was generated by LoadConfig.
	}

	// To satisfy the subtask requirement of logging "new DeviceID was generated" by LoadConfig
	// the existing printf for Generated new DeviceID suffices.
	// The caller (handleInitCmd or handleListenCmd) will be responsible for saving.

	return &cfg, nil // Return deviceIDWasGenerated if caller needs to know to save. For now, not returning it.
}

// SaveConfig saves the configuration data to .filesync/config.json in the baseFolder.
func SaveConfig(baseFolder string, cfg *Config) error {
	configFilePath, err := getConfigPath(baseFolder)
	if err != nil {
		return err // Error from getConfigPath
	}

	configDirPath := filepath.Dir(configFilePath)
	if _, err := os.Stat(configDirPath); os.IsNotExist(err) {
		fmt.Printf("Config directory '%s' not found, creating it.\n", configDirPath)
		if err := os.MkdirAll(configDirPath, 0750); err != nil { // 0750 permissions
			return fmt.Errorf("failed to create config directory '%s': %w", configDirPath, err)
		}
	} else if err != nil {
		return fmt.Errorf("failed to stat config directory '%s': %w", configDirPath, err)
	}

	data, err := json.MarshalIndent(cfg, "", "  ") // Use indent for readability
	if err != nil {
		return fmt.Errorf("failed to marshal config data: %w", err)
	}

	err = os.WriteFile(configFilePath, data, 0640) // 0640 permissions
	if err != nil {
		return fmt.Errorf("failed to write config file '%s': %w", configFilePath, err)
	}
	fmt.Printf("Config saved successfully to '%s'.\n", configFilePath)
	return nil
}
